# Generated by Django 4.2.2 on 2024-04-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProjects', '0008_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
