# Generated by Django 4.2.10 on 2024-04-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skills_userskills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
