# Generated by Django 4.2.10 on 2024-04-15 19:55

from django.db import migrations, models
import skills.models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_skills_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='acquired',
            field=models.JSONField(default=skills.models.default_skills),
        ),
        migrations.AlterField(
            model_name='skills',
            name='search',
            field=models.JSONField(default=skills.models.default_skills),
        ),
    ]
