# Generated by Django 4.2.10 on 2024-04-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_alter_skills_acquired_alter_skills_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Exp', 'Expertise'), ('DB', 'Database'), ('Lang', 'Language'), ('Pers', 'Personal')], max_length=100)),
            ],
        ),
    ]
