# Generated by Django 4.2.2 on 2024-04-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_remove_master_skills_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSkills',
        ),
    ]
