# Generated by Django 4.2.10 on 2024-04-08 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friendsSystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="friend1",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="friend2",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
