# Generated by Django 4.2.10 on 2024-04-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsSystem', '0002_alter_friendrequest_friendrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
