# Generated by Django 4.2.10 on 2024-04-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friendsSystem", "0002_alter_friend_friend1_alter_friend_friend2"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="friend_id",
            field=models.CharField(default="null", max_length=255),
        ),
        migrations.AlterField(
            model_name="friendrequest",
            name="friendRequest_id",
            field=models.CharField(default="null", max_length=255),
        ),
    ]
