# Generated by Django 4.2.10 on 2024-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendsSystem', '0003_friendrequest_notification_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='notification_sent',
            new_name='notification_interacted',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='notification_pending',
            field=models.BooleanField(default=True),
        ),
    ]
