# Generated by Django 4.2.10 on 2024-03-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='status',
        ),
        migrations.AddField(
            model_name='skill',
            name='acquired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='searching',
            field=models.BooleanField(default=False),
        ),
    ]
