# Generated by Django 4.2.10 on 2024-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notification_interacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='notification_pending',
            field=models.BooleanField(default=True),
        ),
    ]
