# Generated by Django 4.2.2 on 2024-04-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_decline_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declinedmatch',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='declinedmatch',
            name='sender',
        ),
        migrations.DeleteModel(
            name='decline_match',
        ),
        migrations.DeleteModel(
            name='DeclinedMatch',
        ),
    ]
