# Generated by Django 4.2.2 on 2024-04-30 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0005_remove_declinedmatch_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeletedMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletedMatches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
