# Generated by Django 4.2.2 on 2024-04-30 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0006_userdeletedmatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeletedmatches',
            name='deleted_matches',
            field=models.ManyToManyField(related_name='deletedMatch', to=settings.AUTH_USER_MODEL),
        ),
    ]
