# Generated by Django 4.2.2 on 2024-04-30 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_userdeletedmatches_deleted_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeletedmatches',
            name='deleted_matches',
        ),
        migrations.AddField(
            model_name='userdeletedmatches',
            name='deleted_matches',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
