# Generated by Django 4.2.2 on 2024-04-30 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_userdeletedmatches_deleted_matches_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeletedMatches',
        ),
    ]
