# Generated by Django 4.2.2 on 2024-04-30 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import matches.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0009_delete_userdeletedmatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed_matches', models.JSONField(default=matches.models.deleted_matches)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletedmatches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
